version: 2.0

jobs:
  deploy:
    steps:
      - run: bash deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
